/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [],
  theme: {
    colors: {
      white: '#FFFFFF',
      background: '#21243D',
      lightgray: '#EDF1F3',
      gray: '#BDC0C4',
      darkblue: '#201E39',
      red: '#E34032',
      azure: '#51C6CA',
      green: '#42E2A6',
    },
    extend: {},
    fontFamily: {
      'gilroy-black': 'Gilroy-Black',
      'gilroy-black-italic': 'Gilroy-BlackItalic',
      'gilroy-bold': 'Gilroy-Bold',
      'gilroy-bold-italic': 'Gilroy-BoldItalic',
      'gilroy-extrabold': 'Gilroy-Extrabold',
      'gilroy-extrabold-italic': 'Gilroy-ExtraboldItalic',
      'gilroy-heavy': 'Gilroy-Heavy',
      'gilroy-heavy-italic': 'Gilroy-HeavyItalic',
      'gilroy-light': 'Gilroy-Light',
      'gilroy-light-italic': 'Gilroy-LightItalic',
      'gilroy-medium': 'Gilroy-Medium',
      'gilroy-medium-italic': 'Gilroy-MediumItalic',
      'gilroy-regular': 'Gilroy-Regular',
      'gilroy-regular-italic': 'Gilroy-RegularItalic',
      'gilroy-semibold': 'Gilroy-Semibold',
      'gilroy-semibold-italic': 'Gilroy-SemiboldItalic',
      'gilroy-thin': 'Gilroy-Thin',
      'gilroy-thin-italic': 'Gilroy-ThinItalic',
      'gilroy-ultra-light': 'Gilroy-UltraLight',
      'gilroy-ultra-light-italic': 'Gilroy-UltraLightItalic',
    },
  },
  plugins: [],
}
