default_platform(:ios)

platform :ios do
  lane :version do
    app_id = "com.tasa"
    xcodeproj = "Riro.xcodeproj"

    # app_store_connect_api_key(
    #   key_filepath: "./AuthKey.p8",
    #   key_id: "5SBB4DLYK5",
    #   issuer_id: "5b365302-6b69-4796-beae-c9810c46ee25",
    # )

    increment_version_number(
      xcodeproj: xcodeproj,
      version_number: ENV["VERSION_NAME"],
    )

    # hiiden since auto incremented on xcode cloud build
    # increment_build_number(
    #   xcodeproj: xcodeproj,
    #   build_number: latest_testflight_build_number(
    #     app_identifier: app_id,
    #     api_key: lane_context[SharedValues::APP_STORE_CONNECT_API_KEY],
    #   ) + 1,
    # )
  end
end
