default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Play Store"
  lane :beta do
    android_set_version_code(
      version_code: ENV["VERSION_CODE"],
      gradle_file: "app/build.gradle",
    )

    android_set_version_name(
      version_name: ENV["VERSION_NAME"],
      gradle_file: "app/build.gradle",
    )

    gradle(
      task: "assemble",
      build_type: "Release",
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => ENV["KEYSTORE_FILE"],
        "android.injected.signing.store.password" => ENV["STORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["KEY_PASSWORD"],
      },
    )
  end
end
